# Generated by Django 3.1.2 on 2020-10-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='id_rota',
        ),
    ]
