# Generated by Django 3.1.2 on 2020-10-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_remove_rota_id_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='mapa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='desafio.mapa'),
        ),
    ]
