# Generated by Django 3.1.2 on 2020-10-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_rota_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='mapa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='desafio.mapa'),
        ),
    ]
