# Generated by Django 3.1.2 on 2020-10-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_auto_20201022_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='distancia',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rota',
            name='mapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='desafio.mapa'),
        ),
    ]
