# Generated by Django 3.1.2 on 2020-10-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0005_auto_20201022_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.CharField(max_length=300)),
                ('custo', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='rota',
            name='distancia',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together={('mapa', 'origem', 'destino', 'distancia')},
        ),
    ]
