# Generated by Django 3.1.2 on 2020-10-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_auto_20201022_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculo',
        ),
    ]
