# Generated by Django 3.1.2 on 2020-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0007_delete_calculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='distancia',
            field=models.IntegerField(),
        ),
    ]
