# Generated by Django 3.1.2 on 2020-10-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0009_auto_20201023_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
