# Generated by Django 3.1.2 on 2020-10-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0010_auto_20201023_2028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together=set(),
        ),
    ]
